### ISSUE TITLE
TDM cant download local file

### ISSUE THREAD

**Issue by pangyf10** [inbasic/turbo-download-manager#11]
I install TDM 0.1.7.1，try to find if it is good，so I download something。when I try to download local file，from 127.0.0.1，it say ”url is not valid“。But default  download manager can download right。I use it in FF。
Also 192.168.x.x doesnt work，this is more important ，share file in local network is important

**Comment by inbasic** [comment]
Thanks for the report. The URL detection module is improved. You can try the latest dev version here,
https://github.com/inbasic/turbo-download-manager/blob/master/builds/packed/firefox.xpi?raw=true

download the XPI and drop it into your Firefox browser.

note that your local web server should support multi-threading, otherwise the download fails. To start a simple web server use `sudo php -S 127.0.0.1:80 -t .` command (assuming you have php installed)

**Comment by pangyf10** [comment]
Yes, the bug has gone.
