### ISSUE TITLE
Lag and not show speed and time lelf.

### ISSUE THREAD

**Issue by lagun** [inbasic/turbo-download-manager#4]
Firefox 41.0.1 
it lag 5 sec after i click download files and it not how much speed and time lelf.
this url 
http://dl.filehorse.com/win/anti-virus/avast-antivirus/Avast-Free-Antivirus-10.4.2233.exe?st=RcVRm2hdj09OfWXYLZo3NQ&e=1444147125&fn=avast_free_antivirus_setup.exe
picture
http://postimg.org/image/8i5umr6pf/

About speed download is good

**Comment by inbasic** [comment]
I added support for speed and time measures. Please try the latest dev version here,
https://github.com/inbasic/turbo-download-manager/blob/master/src.safariextension/executables/extension.xpi?raw=true

And about the 5 second lag: the downloader first need to get the file info by sending a `HEAD` request to the server. This time is probably for the `HEAD` request. It really depends on the server response time.

**Comment by lagun** [comment]
thx u for answer me.
if possible add right click copy url and remove files from space plz.

i try to download big filesite it freeze browser. i think more big files site more freeze
such as this url
https://ia801508.us.archive.org/2/items/BAGAS31DRP15.9Full_201509/%5bBAGAS31%5d%20DRP_15.9_Full.iso 

it stuck , when i download from this url. it can't download complete.
http://www.youtube-mp3.org/get?video_id=Ib4eS_PGVRw&ts_create=1444214497&r=MTgyLjUyLjEyLjI3&h2=1342c2eee51fcbfa6b97c03105eeb36a&s=143222
picture
http://postimg.org/image/npkys5sot/

How i save to another folder? i set download to desktop but  C:\Users\name\Downloads
sry for my bad eng.

**Comment by inbasic** [comment]
> if possible add right click copy url and remove files from space plz.

Please open a new bug for this

> it stuck , when i download from this url it can't download complete.

Can you confirm on the latest dev version, https://github.com/inbasic/turbo-download-manager/blob/master/src.safariextension/executables/extension.xpi?raw=true

> i try to download big filesite it freeze browser.

It is very unlikely the size of file has anything to do with the performance. The downloader writes chunks as soon as they are ready. Anyhow, please try the downloader on [a clean profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) to make sure none of your extensions is conflicting with the downloader. Then try to download when the UI is open and once when it is closed. Is there any visible performance difference?

**Comment by lagun** [comment]
i confirm v.0.1.4

**Comment by inbasic** [comment]
So there is no more freezing problem in 0.1.4 or 0.1.5b1?

**Comment by lagun** [comment]
0.1.5b1 same problem it stuck , when i download from youtubetomp3 and userscloud.
https://userscloud.com/9hy8i35k3an1
picture
http://postimg.org/image/npkys5sot/
http://postimg.org/image/v7c1jg5c3/

So there is no more freezing problem ? --> i think it very lag.
watch my video to see this.
https://sendvid.com/syfk7ken

**Comment by inbasic** [comment]
> 0.1.5b1 same problem it stuck , when i download from youtubetomp3 and userscloud.

Turned out that youtubetomp3 only allows a few threads for each download. If you reduce the number of threads to 3 and do not pause the download, it works fine. But if you pause the download multiple times, the server returns 403 (forbidden). I added a new item to the UI. Now you can check the number of retires extension does for a single download. If this number exceeds 30, the download is pausing. Try the latest built, 0.1.5b3, https://github.com/inbasic/turbo-download-manager/blob/master/src.safariextension/executables/extension.xpi?raw=true

I was not able to check userscloud though.

> So there is no more freezing problem ? --> i think it very lag.

Wow! it does lag your browser! I assume this is a conflict with another extension of yours. Can you try the downloader on a clean profile and repeat this test?

**Comment by lagun** [comment]
0.1.5b3 i can download from youtubetomp3 and userscloud.complete.
http://postimg.org/image/z8b621t81/
0.1.5b3 i think it smooth download more than 1.4. 

it stuck 0% number exceeds 30, the download is pausing and i click resume many time but it stuck o% long time.
http://postimg.org/image/n8rup2idz/
this url
http://110.164.180.77/stream/video01/2015/03/30/1427703329/1427703329_360.mp4

Wow! it does lag your browser! I assume this is a conflict with another extension of yours. Can you try the downloader on a clean profile and repeat this test? -->  i test on a clean profile and i think it not different,it very lag but it only  a big files download.
https://sendvid.com/kx4qo69j

**Comment by inbasic** [comment]
I believe the lag issue is fixed on 0.1.6b1,
https://github.com/inbasic/turbo-download-manager/blob/master/src.safariextension/executables/extension.xpi?raw=true

Basically, the problem was the time required by OS to create such a huge file. In 0.1.6b1, the downloader increases the number of chunks and start writing initial chunks. This way OS has enough time to allocate the file.

Can you confirm?

**Comment by lagun** [comment]
Confirm!! awesome,don't lag anymore.
https://sendvid.com/tp455gmk

About this url.
http://110.164.180.77/stream/video01/2015/03/30/1427703329/1427703329_360.mp4
0.1.6b1, now it not stuck 0% but stuck 75.2% for long time and exceeds 30, the download is pausing and i click resume many time.
picture
http://postimg.org/image/6ku8oeuvx/
http://postimg.org/image/qq71ry8v1/

**Comment by inbasic** [comment]
> 0.1.6b1, now it not stuck 0% but stuck 75.2% for long time and exceeds 30, the download is pausing and i click resume many time.

So this server does not support multi-threading. In the latest dev version, there is a better support for this type of servers; meaning, the number of threads requested by user is now ignored (only a single thread is actually applied). And when the download fails, the downloader fails the download process instead of pausing it as there is no support for resuming anymore.

Just for clarification, if a server is not supporting multi-threading, there is no advantage of using TDM at all. You can find multi-threading support info in the download log ("i" button).

**Comment by lagun** [comment]
ok,i see. :)

**Comment by inbasic** [comment]
@lagun I am closing this bug. Please do let me know if you have any more suggestions by opening new bugs.
