### ISSUE TITLE
I got stuck.

### ISSUE THREAD

**Issue by lagun** [inbasic/turbo-download-manager#43]
firefox 46.0.1 32bit
tdm version 0.2.7
i can't download complete.

this url 
https://singularlabs.com/download/10294/
from this site 
https://singularlabs.com/software/system-ninja/confirm-download/
picture
http://postimg.org/image/fvnnyy9mp/

**Comment by inbasic** [comment]
This server claims that it supports segmentation, though the server is not responding to the ranged headers. This is a server side issue and cannot be fixed. 

You can get files from this server by reducing the number of threads to one.

**Comment by MariasStory** [comment]
Shouldn't turbo-download-manager check it automatically and have a fallback for this situation?

**Comment by inbasic** [comment]
@MariasStory TDM does check for multi-threading support. The problem is with this particular server as it is claiming they support multi-threading. Beside sending the supporting header, they return 206 status code which is sent when a partial data is transmitted. So there is no way for TDM to detect the server is not handling the request as it is supposed to.

So is this happening for another domain too?

**Comment by lagun** [comment]
Thank you for explain.

**Comment by MariasStory** [comment]
@inbasic I did not see this happening for another domains. But, where one case, another may follow.

Maybe, there is a way to check for such misleading server behavior?

**Comment by inbasic** [comment]
That seems very rare situation for a server to send two wrong signals;
1. wrong header 
2. 206 status code instead of 200.

Either of these two signals will lead TDM to throw an error message to warn user or reduce the number of threads to one and continue the job if possible.

I am not aware of any other checking methods.

**Comment by MariasStory** [comment]
OK. If there is the warning and proposed solution in it, this should not be a problem.

The download attempt with one thread could be started automatically, plus the warn. :-)
